name: transitkit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
    - git+https://github.com/yourusername/transitkit.git
    - lightkurve
    - batman-package